Return-Path: <corinna@sourceware.org>
Received: by sourceware.org (Postfix, from userid 2155)
	id 7554B3854827; Mon, 23 Jun 2025 20:04:49 +0000 (GMT)
DKIM-Filter: OpenDKIM Filter v2.11.0 sourceware.org 7554B3854827
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=cygwin.com;
	s=default; t=1750709089;
	bh=xtiOlo8/63ldrB6jNJZ6llY8gAgQE4ux9WLmvbDP4uk=;
	h=Date:From:To:Cc:Subject:Reply-To:References:In-Reply-To:From;
	b=soctzc7/q+zFlGqDOMAu+IAKZ0ric6w3lFqsHqIW1ae1JUZSb0ZDFWor23MBSM5DM
	 cwG9HTuiN5fn242zZk5fCok2zAkCQGHWgW0Tqm4kQIEheVsfCrnrTuc61mOhz+99IA
	 OtegbGyNWxJhtUKjnNBLJcVVWCeBGhJ86fvjYV5s=
Received: by calimero.vinschen.de (Postfix, from userid 500)
	id 50FEEA80D72; Mon, 23 Jun 2025 22:04:47 +0200 (CEST)
Date: Mon, 23 Jun 2025 22:04:47 +0200
From: Corinna Vinschen <corinna-cygwin@cygwin.com>
To: johnhaugabook@gmail.com
Cc: cygwin-patches@cygwin.com
Subject: Re: [PATCH 0/4] cygwin-htdocs: faq.html edits
Message-ID: <aFmzX4CARCb0810R@calimero.vinschen.de>
Reply-To: cygwin-patches@cygwin.com
Mail-Followup-To: johnhaugabook@gmail.com, cygwin-patches@cygwin.com
References: <20250622082003.1685-1-johnhaugabook@gmail.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Disposition: inline
In-Reply-To: <20250622082003.1685-1-johnhaugabook@gmail.com>
List-Id: <cygwin-patches.cygwin.com>

Hi John,

On Jun 22 04:19, johnhaugabook@gmail.com wrote:
> From: jhauga <johnhaugabook@gmail.com>
> 
> This patch series contains several focused documentation edits to faq.html

A couple of problems with your patches:

- First and foremost, you're patching the wrong file.  faq/faq.html is
  in fact an autogenerated file. The source is actually an XML file
  in the Cygwin repository itself: winsup/doc/faq.xml.

- Given the file you change is actually part of Cygwin, please add
  a "Cygwin:" prefix to your commit message summary line.

- Your commit messages should explain what your doing and a bit of
  why wouldn't hurt either.  Just the summary line is a bit on the
  terse end.

- Please give a real name as author name, and...

- ...please add a "Signed-off-by:" line.  This isn't necessary for your
  second patchset only changing a file actually maintained in
  cygwin-htdocs.

- Especially patch 4/4 is questionable.  I don't even understand what
  your summary line means, and the patch looks pretty big.  What is it
  doing?  Some explanation and splitting the patch if possible, please?


Thanks,
Corinna


> 
> Changes include:
> - In section 6.21 - added additional required packages for installation of newlib-cygwin. The packages added are build: libtool; dumper utility: libiconv, libiconv2; documentation: perl-XML-SAX-Expat, docbook-utils. Also ordered packages alphabetically as this makes it easier when using GUI of setup-x86_64.exe when selecting packages.
> - In section 6.21 - added example of calling setup-x86_64.exe to do a preliminary search when installing packages, as there are nearly a dozen packages, and because it can take over 30 minutes for the installation to complete; and if all the required packages are not downloaded, the install will fail at like minute 29.
> - In section 6.21 - added an additional paragraph and tips regarding the install process.
> - Added section 3.4 - instructions on how to build local version of site from "https://cygwin.com/git.html". Instructions mainly specify how to configure local server's httpd.conf file, and downloading a command line tool. In example used httpd install with "winget install ApacheLounge.httpd".
> 
> These patches were created against the latest upstream `master` branch.
> 
> Thanks for your review and feedback.
> 
> jhauga (4):
>   faq.html: add 5 required packages and sort packages
>   faq.html: add ready-made -P download commands
>   faq.html: section 6.21 tips and additions
>   faq.html: add 3.4 run cloned site locally
> 
>  faq/faq.html | 93 +++++++++++++++++++++++++++++++++++++++-------------
>  1 file changed, 71 insertions(+), 22 deletions(-)
> 
> -- 
> 2.46.0.windows.1
> 
